server:
  port: 8080 #端口号
  tomcat:
    uri-encoding: UTF-8
  address: 127.0.0.1
  shutdown: graceful #优雅停机
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
  jpa:    hibernate:      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://10.0.193.11:3306/vskedtest?useUnicode=true&characterEncoding=utf8&allowMutiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: Y4yhl9tbf110_
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:      connection-test-query: select 1
    
  http:
    encoding:
      charset: UTF-8
      enabled: true

logging:
  config: classpath:log4j2.xml


