server:
  port: 8181 #端口号

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://rm-2ze868z3lnw294w33oo.mysql.rds.aliyuncs.com:3306/testdev?useUnicode=true&characterEncoding=utf8&allowMutiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    username: testdev
    password: u2NOupuL%1v9r#DS
    hikari:
      connection-test-query: select 1

logging:
  config: classpath:log4j2.xml
