server:
  port: 8182 #端口号
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  undertow:
    max-http-post-size: -1
    buffer-size: 512
    direct-buffers: true
    accesslog:
      enabled: true
      dir: /logs/access_log_@artifactId@
      prefix: accesslog
      suffix: .log
      rotate: true
      pattern: '%t %a %A %p %H %m %R %s %b'
  shutdown: graceful #开启优雅停机 默认为immediate立即停机

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://10.0.193.11:3306/userrestddd?useUnicode=true&characterEncoding=utf8&allowMutiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
#    password: ENC(tbKZkQjZQiJ229X32lo+uM0H/D0DI1qd)
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1

logging:
  config: classpath:log4j2-test.xml

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: junantai
