server:
  port: 8080 #端口号
  tomcat:
    uri-encoding: UTF-8

  
spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
  datasource:
    postgredb1:
      jdbc-url: jdbc:postgresql://10.0.192.251:5432/risk
      username: postgres
      password: Y4yhl9tbf110
      driver-class-name: org.postgresql.Driver
      maximumPoolSize: 20 #hikria配置
      connection-test-query: select 1 #hikria配置


    phoenixdb1:
      jdbc-url: jdbc:phoenix:demoevn1:2181
      username: 
      password: 
      driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
      configuration:
        connection-test-query: select 1
    
  http:
    encoding:
      charset: UTF-8
      enabled: true

mybatis:
  configuration:
    call-setters-on-nulls: true

logging:
  config: classpath:log4j2.xml


