server:
  port: 8080 #端口号
  tomcat:
    uri-encoding: UTF-8
  
spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
  datasource:
    url: jdbc:postgresql://192.168.111.45:5432/testbb
    username: postgres
    password: Y4yhl9tbf110
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
    
  http:
    encoding:
      charset: UTF-8
      enabled: true

mybatis:
  configuration:
    call-setters-on-nulls: true

logging:
  config: classpath:log4j2.xml


