server:
  port: 8181 #端口号
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful #开启优雅停机 默认为immediate立即停机

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s #设置优雅停机缓冲时间默认30s
  devtools:
    restart:
      enabled: true #设置开启热部署
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:tcp://10.0.192.1:9092/d:/h2test/test202210141505
    username: root
    password: root
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: select 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      path: /h2console #h2 web管理界面访问地址
      enabled: true #开启h2 web管理界面

logging:
  config: classpath:log4j2.xml

