server:
  port: 8080 #端口号
  tomcat:
    uri-encoding: UTF-8

spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
    
  http:
    encoding:
      charset: UTF-8
      enabled: true

logging:
  config: classpath:log4j2.xml


