server:
  port: 64446 #端口号
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  undertow:
    accesslog:
      enabled: true
      dir: /logs/access_log_@artifactId@
      prefix: accesslog
      suffix: .log
      rotate: true
      pattern: '%t %a %A %p %H %m %R %s %b'
  shutdown: graceful #开启优雅停机 默认为immediate立即停机

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s #设置优雅停机缓冲时间默认30s
  devtools:
    restart:
      enabled: true #设置开启热部署
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://10.0.193.11:3306/mavenparent?useUnicode=true&characterEncoding=utf8&allowMutiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: Y4yhl9tbf110_
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1

logging:
  config: classpath:log4j2.xml
