package com.jat.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseResource<M extends BaseResource<M>> extends Model<M> implements IBean {

	/**
	 * 编号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 编号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 资源名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 资源名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 资源URL
	 */
	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	/**
	 * 资源URL
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	/**
	 * 图标
	 */
	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}
	
	/**
	 * 图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}
	
	/**
	 * 资源标识 0 目录 1 菜单 2 按钮
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 资源标识 0 目录 1 菜单 2 按钮
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 顺序
	 */
	public M setSequence(java.lang.Integer sequence) {
		set("sequence", sequence);
		return (M)this;
	}
	
	/**
	 * 顺序
	 */
	public java.lang.Integer getSequence() {
		return getInt("sequence");
	}
	
	/**
	 * 资源的上一级
	 */
	public M setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
		return (M)this;
	}
	
	/**
	 * 资源的上一级
	 */
	public java.lang.Integer getParentId() {
		return getInt("parentId");
	}
	
	/**
	 * 0表示有效  1表示无效
	 */
	public M setIsDel(java.lang.Integer isDel) {
		set("isDel", isDel);
		return (M)this;
	}
	
	/**
	 * 0表示有效  1表示无效
	 */
	public java.lang.Integer getIsDel() {
		return getInt("isDel");
	}
	
}

