package com.jat.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

	/**
	 * 账号编号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 账号编号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 账号名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 账号名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 账号密码
	 */
	public M setPass(java.lang.String pass) {
		set("pass", pass);
		return (M)this;
	}
	
	/**
	 * 账号密码
	 */
	public java.lang.String getPass() {
		return getStr("pass");
	}
	
	/**
	 * 0表示有效  1表示无效
	 */
	public M setIsDel(java.lang.Integer isDel) {
		set("isDel", isDel);
		return (M)this;
	}
	
	/**
	 * 0表示有效  1表示无效
	 */
	public java.lang.Integer getIsDel() {
		return getInt("isDel");
	}
	
}

