server:
  port: 8080 #端口号
   #servlet.context-path: / 项目名，如果不设定，默认是 /

spring:
  redis:
    timeout: 6000ms
    password: Y4yhl9tbf110_
    cluster:
      max-redirects: 3
      nodes:
        - 192.168.111.81:6379
        - 192.168.111.81:6380
        - 192.168.111.81:6381
        - 192.168.111.82:6379
        - 192.168.111.82:6380
        - 192.168.111.82:6381
    lettuce:
      pool:
        max-active: 500
        max-idle: 10
        min-idle: 5
        max-wait: -1

logging:
  config: classpath:log4j2.xml
