server:
  port: 8080 #端口号
   #servlet.context-path: / 项目名，如果不设定，默认是 /

spring:
  redis:
    timeout: 6000ms
    password: Y4yhl9tbf110_
    cluster:
      max-redirects: 3
      nodes:
        - 1.196.217.116:6379
        - 1.196.217.116:6380
        - 1.62.145.87:6379
        - 1.62.145.87:6380
        - 1.196.204.187:6379
        - 1.196.204.187:6380
    lettuce:
      pool:
        max-active: 500
        max-idle: 10
        min-idle: 5
        max-wait: -1

logging:
  config: classpath:log4j2.xml
