package com.jat.model;

import com.jat.model.base.BaseResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resource extends BaseResource<Resource> {
	public static final Resource dao = new Resource().dao();
}

