spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
  redis:
    database: 0
    host: 192.168.111.95
    port: 6379
    password: Y4yhl9tbf110_
    timeout: 10000
    
    
websocketservera:
  host: 0.0.0.0
  port: 9200
  path: /servera