server:
  port: 8181 #端口号
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
  redis:
    database: 0
    host: 10.0.193.11
    port: 6379
    password: Y4yhl9tbf110_
    timeout: 10000
    
    
websocketservera:
  host: 0.0.0.0
  port: 9200
  path: /servera