server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vskedadmin?useUnicode=true&characterEncoding=utf8&allowMutiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    username: vskedadmin
    password: vskedadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
  redis:
    host: 127.0.0.1
    port: 6379
    password: Y4yhl9tbf110_
    database: 0

cache:
  cacheName: "technology"
