server:
  port: 8080 #端口号
  
spring:
  kafka:
    bootstrap-servers:
      - 192.168.60.10:9092
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: true
      group-id: sk01
      

kafkalistenerlist: 
  topiclist: mytpoic1,mytpoic2
  
logging:
  config: classpath:log4j2.xml