server:
  port: 9010 #端口号
  servlet.context-path: /appserveruser  #项目名，如果不设定，默认是 /
  
spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/appserverdev?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 10000
    
    
    
logging:
  config: classpath:log4j2.xml
