server:
  port: 9010 #端口号
  tomcat:
    uri-encoding: UTF-8
  #servlet.context-path: /appserveruser  #项目名，如果不设定，默认是 /
  
spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
  datasource:
    url: jdbc:mysql://localhost:3306/appserverdev?useUnicode=true&characterEncoding=utf8&allowMutiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  http:
    encoding:
      charset: UTF-8
      enabled: true

mybatis:
  configuration:
    call-setters-on-nulls: true

logging:
  config: classpath:log4j2.xml


