package com.jat.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("account", "id", Account.class);
		arp.addMapping("resource", "id", Resource.class);
		arp.addMapping("role", "id", Role.class);
		// Composite Primary Key order: resId,roleId
		arp.addMapping("roleResource", "resId,roleId", RoleResource.class);
		arp.addMapping("user", "id", User.class);
		// Composite Primary Key order: accountId,userId
		arp.addMapping("userAccount", "accountId,userId", UserAccount.class);
		// Composite Primary Key order: roleId,userId
		arp.addMapping("userRole", "roleId,userId", UserRole.class);
	}
}


