package com.jat.model;

import com.jat.model.base.BaseRoleResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleResource extends BaseRoleResource<RoleResource> {
	public static final RoleResource dao = new RoleResource().dao();
}

